# port for server
server.port:<port>

# Database configuration
spring.datasource.url=jdbc:postgresql://<host>/<database>?sslmode=require
#sslmode=reuire is mandatory for neon db

spring.datasource.username=<username>
spring.datasource.password=<password>
spring.datasource.driver-class-name=org.postgresql.Driver
