# port for server
server.port:8088

# Database configuration
# String in neon: postgresql://neondb_owner:npg_ehKJVksZ47oH@ep-mute-lake-aote7aua.c-2.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.url=jdbc:postgresql://ep-mute-lake-aote7aua.c-2.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
#sslmode=reuire is mandatory for neon db

spring.datasource.username=neondb_owner
spring.datasource.password=npg_ehKJVksZ47oH
spring.datasource.driver-class-name=org.postgresql.Driver